"""Real-weight parity test for ``orb-v3-conservative-inf-omat`` on a MULTI-ELEMENT bulk system
(MgO rock-salt, 8 atoms: 4 Mg + 4 O), against the golden generated by ``tests/gen_golden_orb.py
--system mgo``.

Every other bulk row in the suite is pure Si (Z=14): the 4-atom toy, the 24-atom supercell, the
short-contact pair, and both stress rows. This module is the first binary-chemistry golden -- it
exercises three code paths that a single-Z system cannot reach:

  * ``host_energy_denormalize`` sums ``ref_weight[Z]`` per atom -- only ever hit at Z=14 elsewhere.
  * the ZBL pair-repulsion term across mixed Z pairs (Mg-Mg, Mg-O, O-O), each with its own
    covalent-radii-sum envelope cutoff.
  * the encoder's per-element embedding table at two different atomic numbers simultaneously.

MgO is a textbook ionic oxide, in-distribution for ``conservative-inf-omat`` (OMat24 covers bulk
inorganic oxides), and reuses the exact same periodic path / device modules as the Si toy
(``test_orb_realweight.py`` + ``test_orb_forces_realweight.py``) -- no new device code, just a new
composition. Same conservative-inf-omat checkpoint, same analytic-force VJP
(``orb_forces.energy_and_forces``), same bars (energy rel err < 1e-2, force PCC > 0.999).

    ~/.ttatom_run/refenv/bin/python tests/gen_golden_orb.py --ckpt conservative-inf-omat \
        --system mgo --out ~/.ttatom_run/goldens_real/mgo_omat_orb.npz
    TT_VISIBLE_DEVICES=0 PYTHONPATH=. ~/.ttatom_run/env/bin/python -m pytest \
        tests/test_orb_mgo_realweight.py -q -s

Absent the golden bundle the whole module auto-skips.
"""
from __future__ import annotations

import os
import pathlib

import numpy as np
import pytest

REAL_GOLDEN = os.environ.get(
    "TTATOM_ORB_MGO_GOLDEN",
    str(pathlib.Path.home() / ".ttatom_run/goldens_real/mgo_omat_orb.npz"),
)

pytestmark = pytest.mark.skipif(
    not pathlib.Path(REAL_GOLDEN).exists(),
    reason=f"Orb MgO golden bundle not found at {REAL_GOLDEN}",
)


def _pcc(a, b):
    a = np.asarray(a, dtype=np.float64).ravel()
    b = np.asarray(b, dtype=np.float64).ravel()
    if a.std() == 0 and b.std() == 0:
        return 1.0
    return float(np.corrcoef(a, b)[0, 1])


@pytest.fixture(scope="module")
def gw():
    from tt_atom.orb_weights import OrbWeights

    return OrbWeights.load(REAL_GOLDEN)


def test_mgo_multi_element_composition(gw):
    """Sanity: this golden is genuinely binary (Mg + O), not a re-run of the Si toy. The
    per-element reference-energy denormalize and the mixed-Z ZBL pair-repulsion only branch on
    atomic number, so a single-Z golden cannot reach them."""
    Z = gw.inp("atomic_numbers").long()
    uniq = sorted(set(Z.tolist()))
    assert uniq == [8, 12], uniq  # O + Mg
    assert Z.numel() == 8


def test_mgo_energy_and_forces(gw, device):
    """Full device pipeline (encoder -> 5 interaction layers -> EnergyHead, and
    ``orb_forces.energy_and_forces`` for analytic conservative forces) vs the real orb-models
    oracle on the MgO rock-salt supercell."""
    from tt_atom.orb_model import (Encoder, AttentionInteractionLayer, OrbGraphContext, EnergyHead,
                                   host_cutoff, host_zbl_energy, host_zbl_forces,
                                   host_energy_denormalize, host_conservative_force_denormalize,
                                   _to_dev)
    from tt_atom.orb_forces import energy_and_forces
    import ttnn

    cfg = gw.config
    w = gw.weights
    L = cfg["num_message_passing_steps"]
    latent_dim = cfg["latent_dim"]
    enc = Encoder(w, device, node_in=cfg["node_embed_size"], edge_in=cfg["edge_embed_size"],
                 latent_dim=latent_dim, hidden_dim=1024)
    layers = [AttentionInteractionLayer(w, f"gnn_stacks.{i}", device, latent_dim=latent_dim,
                                        hidden_dim=1024) for i in range(L)]
    ehead = EnergyHead(w, device, latent_dim=latent_dim, hidden_dim=1024)

    atomic_numbers = gw.inp("atomic_numbers").long()
    senders = gw.inp("senders").long()
    receivers = gw.inp("receivers").long()
    vectors = gw.inp("vectors")
    pos = gw.inp("pos").float()
    node_feat = gw.host("node_feat")
    N = atomic_numbers.shape[0]

    # energy: full backbone forward + EnergyHead + host denormalize + host ZBL
    node_dev = _to_dev(node_feat, device, ttnn.bfloat16)
    edge_dev = _to_dev(gw.host("edge_feat"), device, ttnn.bfloat16)
    nodes, edges = enc(node_dev, edge_dev)
    cutoff = host_cutoff(vectors.norm(dim=-1), r_max=6.0)
    graph = OrbGraphContext(device, senders=senders, receivers=receivers, cutoff=cutoff,
                            num_nodes=N)
    for i, layer in enumerate(layers):
        nodes, edges = layer(nodes, edges, graph)
        pcc_n = _pcc(ttnn.to_torch(nodes).float(), gw.activation(f"gnn{i}.out0"))
        print(f"[orb-mgo] backbone layer {i}/{L-1} node PCC={pcc_n:.6f}")
    final_pcc = _pcc(ttnn.to_torch(nodes).float(), gw.activation(f"gnn{L-1}.out0"))
    assert final_pcc > 0.99, final_pcc

    raw_e = ttnn.to_torch(ehead(nodes)).double().view(())
    gnn_energy = host_energy_denormalize(
        raw_e, atomic_numbers, N,
        running_mean=w["energy_head.normalizer.bn.running_mean"],
        running_var=w["energy_head.normalizer.bn.running_var"],
        ref_weight=w["energy_head.reference.linear.weight"].view(-1),
    )
    zbl_energy = host_zbl_energy(atomic_numbers, senders, receivers, vectors)
    total_energy = float(gnn_energy + zbl_energy)
    gold_energy = float(gw.out("energy")[0])
    e_rel_err = abs(total_energy - gold_energy) / abs(gold_energy)
    print(f"[orb-mgo] energy: {total_energy:.6f} eV (oracle {gold_energy:.6f}, "
          f"rel err {e_rel_err:.2e}); GNN={float(gnn_energy):.6f} ZBL={float(zbl_energy):.6e}")
    assert e_rel_err < 1e-2, e_rel_err

    # analytic conservative forces (F = -dE/dpos) via the same VJP as the Si toy
    vectors_gold = gw.inp("vectors").float()
    cell_shift = (vectors_gold - (pos[receivers] - pos[senders])).detach()
    _, raw_forces = energy_and_forces(
        enc, layers, ehead, device, pos=pos, senders=senders, receivers=receivers,
        atomic_numbers=atomic_numbers, node_feat=node_feat, cell_shift=cell_shift)
    forces = host_conservative_force_denormalize(
        raw_forces, N, running_var=w["energy_head.normalizer.bn.running_var"])
    zbl_forces = host_zbl_forces(atomic_numbers, senders, receivers, pos, cell_shift=cell_shift)
    total_forces = (forces + zbl_forces).detach()
    gold_forces = gw.out("forces").double()
    pcc_f = _pcc(total_forces, gold_forces)
    mae_f = float((total_forces - gold_forces).abs().mean())
    fmax = float(gold_forces.abs().max())
    print(f"[orb-mgo] conservative forces: PCC={pcc_f:.6f} MAE={mae_f:.4f} eV/A "
          f"(oracle |F|max={fmax:.4f})")
    assert pcc_f > 0.999, pcc_f
