"""Real-weight parity tests for the Orb-v3-conservative-inf-omat port (bottom-up: encoder +
first attention-interaction layer), against the golden generated by ``tests/gen_golden_orb.py``.

    ~/.ttatom_run/refenv/bin/python tests/gen_golden_orb.py --ckpt conservative-inf-omat \
        --out ~/.ttatom_run/goldens_real/si_omat_orb.npz
    TT_VISIBLE_DEVICES=0 PYTHONPATH=. ~/.ttatom_run/env/bin/python -m pytest tests/test_orb_realweight.py -q

Absent the golden bundle the whole module auto-skips. Same real Si/omat system as the ported
UMA backbone's ``si_omat.npz`` golden (see tests/gen_golden_real.py --system bulk), so the two
energies are a genuine same-system comparison point (see docs/orb-port.md).
"""
from __future__ import annotations

import os
import pathlib

import numpy as np
import pytest
import torch

REAL_GOLDEN = os.environ.get(
    "TTATOM_ORB_GOLDEN", str(pathlib.Path.home() / ".ttatom_run/goldens_real/si_omat_orb.npz")
)

pytestmark = pytest.mark.skipif(
    not pathlib.Path(REAL_GOLDEN).exists(),
    reason=f"Orb golden bundle not found at {REAL_GOLDEN}",
)


def _pcc(a, b):
    a = np.asarray(a, dtype=np.float64).ravel()
    b = np.asarray(b, dtype=np.float64).ravel()
    if a.std() == 0 and b.std() == 0:
        return 1.0
    return float(np.corrcoef(a, b)[0, 1])


@pytest.fixture(scope="module")
def gw():
    from tt_atom.orb_weights import OrbWeights

    return OrbWeights.load(REAL_GOLDEN)


@pytest.fixture(scope="module")
def device():
    from tt_atom.device import open_device
    import ttnn

    dev = open_device(int(os.environ.get("TT_VISIBLE_DEVICES", "0")))
    yield dev
    ttnn.close_device(dev)


def test_encoder(gw, device):
    from tt_atom.orb_model import Encoder, _to_dev
    import ttnn

    cfg = gw.config
    w = gw.weights
    enc = Encoder(w, device, node_in=cfg["node_embed_size"], edge_in=cfg["edge_embed_size"],
                 latent_dim=cfg["latent_dim"], hidden_dim=1024)

    node_feat = gw.host("node_feat")
    edge_feat = gw.host("edge_feat")
    node_dev = _to_dev(node_feat, device, ttnn.bfloat16)
    edge_dev = _to_dev(edge_feat, device, ttnn.bfloat16)

    node_out, edge_out = enc(node_dev, edge_dev)
    node_out = ttnn.to_torch(node_out).float()
    edge_out = ttnn.to_torch(edge_out).float()

    gold_node = gw.activation("encoder.out0")
    gold_edge = gw.activation("encoder.out1")

    pcc_node = _pcc(node_out, gold_node)
    pcc_edge = _pcc(edge_out, gold_edge)
    print(f"\n[orb] encoder node PCC={pcc_node:.6f} edge PCC={pcc_edge:.6f}")
    assert pcc_node > 0.999, pcc_node
    assert pcc_edge > 0.999, pcc_edge

    # stash for test_interaction_layer0 (module-scoped fixtures rerun cheaply; recompute there too)


def test_interaction_layer0(gw, device):
    from tt_atom.orb_model import Encoder, AttentionInteractionLayer, OrbGraphContext, host_cutoff, _to_dev
    import ttnn

    cfg = gw.config
    w = gw.weights
    enc = Encoder(w, device, node_in=cfg["node_embed_size"], edge_in=cfg["edge_embed_size"],
                 latent_dim=cfg["latent_dim"], hidden_dim=1024)
    node_dev = _to_dev(gw.host("node_feat"), device, ttnn.bfloat16)
    edge_dev = _to_dev(gw.host("edge_feat"), device, ttnn.bfloat16)
    nodes, edges = enc(node_dev, edge_dev)

    senders = gw.inp("senders").long()
    receivers = gw.inp("receivers").long()
    vec = gw.inp("vectors")
    lengths = vec.norm(dim=-1)
    cutoff = host_cutoff(lengths, r_max=6.0)

    N = gw.inp("atomic_numbers").shape[0]
    graph = OrbGraphContext(device, senders=senders, receivers=receivers, cutoff=cutoff, num_nodes=N)

    layer0 = AttentionInteractionLayer(w, "gnn_stacks.0", device,
                                       latent_dim=cfg["latent_dim"], hidden_dim=1024)
    nodes2, edges2 = layer0(nodes, edges, graph)
    nodes2_t = ttnn.to_torch(nodes2).float()
    edges2_t = ttnn.to_torch(edges2).float()

    gold_nodes = gw.activation("gnn0.out0")
    gold_edges = gw.activation("gnn0.out1")
    pcc_n = _pcc(nodes2_t, gold_nodes)
    pcc_e = _pcc(edges2_t, gold_edges)
    print(f"\n[orb] gnn layer0 node PCC={pcc_n:.6f} edge PCC={pcc_e:.6f}")
    assert pcc_n > 0.99, pcc_n
    assert pcc_e > 0.99, pcc_e


def test_full_backbone_5layers(gw, device):
    """Chain all 5 message-passing layers (the full omat-conservative backbone depth) and
    check the final node/edge embedding -- the tensor the energy head consumes -- against the
    real fairchem-independent (orb-models) oracle."""
    from tt_atom.orb_model import Encoder, AttentionInteractionLayer, OrbGraphContext, host_cutoff, _to_dev
    import ttnn

    cfg = gw.config
    w = gw.weights
    L = cfg["num_message_passing_steps"]
    enc = Encoder(w, device, node_in=cfg["node_embed_size"], edge_in=cfg["edge_embed_size"],
                 latent_dim=cfg["latent_dim"], hidden_dim=1024)
    node_dev = _to_dev(gw.host("node_feat"), device, ttnn.bfloat16)
    edge_dev = _to_dev(gw.host("edge_feat"), device, ttnn.bfloat16)
    nodes, edges = enc(node_dev, edge_dev)

    senders = gw.inp("senders").long()
    receivers = gw.inp("receivers").long()
    lengths = gw.inp("vectors").norm(dim=-1)
    cutoff = host_cutoff(lengths, r_max=6.0)
    N = gw.inp("atomic_numbers").shape[0]
    graph = OrbGraphContext(device, senders=senders, receivers=receivers, cutoff=cutoff, num_nodes=N)

    layers = [AttentionInteractionLayer(w, f"gnn_stacks.{i}", device,
                                        latent_dim=cfg["latent_dim"], hidden_dim=1024)
              for i in range(L)]
    for i, layer in enumerate(layers):
        nodes, edges = layer(nodes, edges, graph)
        gold_n = gw.activation(f"gnn{i}.out0")
        pcc_n = _pcc(ttnn.to_torch(nodes).float(), gold_n)
        print(f"[orb] backbone layer {i}/{L-1} node PCC={pcc_n:.6f}")

    final_nodes = ttnn.to_torch(nodes).float()
    final_edges = ttnn.to_torch(edges).float()
    gold_nodes = gw.activation(f"gnn{L-1}.out0")
    gold_edges = gw.activation(f"gnn{L-1}.out1")
    pcc_n = _pcc(final_nodes, gold_nodes)
    pcc_e = _pcc(final_edges, gold_edges)
    print(f"\n[orb] FULL 5-layer backbone: final node PCC={pcc_n:.6f} edge PCC={pcc_e:.6f}")
    # node embedding is what the energy head consumes -- held to the tight bar. The edge stream
    # is a pure residual with no further consumer and drifts more under bf16 over 5 layers
    # (measured 0.976, vs 0.997 after 1 layer) -- expected precision compounding, not a bug.
    assert pcc_n > 0.99, pcc_n
    assert pcc_e > 0.97, pcc_e
